### PR TITLE
Drop support for EOL Python 2.7 and 3.5

### PR DESCRIPTION
**Pull request by hugovk**
For https://github.com/SoCo/SoCo/issues/591.

The most important bits are to update the Trove classifiers and add `python_requires` to help pip.

Also upgrades Python syntax using https://github.com/asottile/pyupgrade and removes redundant mock backport and compat submodule and some other unnecessary bits.

### CODE REVIEW

**Comment by pwt** [comment]
Hi @hugovk : this is great, thanks!

Given the scale of the proposed changes, I'm going to target the PR for the 0.22 release, not the imminent 0.21 release for which we're now in feature freeze. We'll take a closer look once 0.21 is released on 17th January.

I think we also need some group discussion about whether the time is right to remove support for Python 3.5, for which EOL was less than 6 months ago.

**Comment by hugovk** [comment]
Yep, sounds sensible.

Is the aim for 0.21 to not work on 2.7? https://github.com/SoCo/SoCo/issues/591 said it already doesn't work on 2.7?

If so, it would make sense to have minimal changes for that: remove the 2.x Trove classifiers, and add `python_requires` excluding 2.7. That means modern pip won't only install 0.21 on Python 2.7, and will fall back to 0.20.

**Comment by pwt** [comment]
> If so, it would make sense to have minimal changes for that: remove the 2.x Trove classifiers, and add `python_requires` excluding 2.7. That means modern pip won't only install 0.21 on Python 2.7, and will fall back to 0.20.

Excellent -- thanks. Pending PR #786 included the trove changes, and I've now added the python 3.5+ requirement.

**Comment by pwt** [comment]
Returning to this after the release of 0.21.

A little bit of rework is required following the 0.21 changes. Also, let's retain Python 3.5 compatibility for the time being. So, please could you:

1. Start with current `master` and run `pyupgrade --py3-plus`
2. Run `black *.py soco/*.py tests/*.py` to make the formatting Black-compliant once again

This will result in code that passes all current SoCo check jobs, as well as the integration tests. (The two steps above are idempotent -- i.e., re-running pyupgrade will not make any changes.)

3. With the 0.21 changes, and if we stick with Python 3.5 compatibility, the following files no longer need to change: `.travis.yml`, `README.rst`.
4. I'd retain the Black import line as-is in `requirements-dev.txt`.
5. The other changes look good.

Take look at the above and let me know what you think.

Sorry for the extra work. This is a very nice 'cleanup' PR, and as it changes lots of files I'd like to get it in early in the v0.22 cycle, so other PRs can sync with it.

**Comment by rytilahti** [comment]
Note that even Debian stable which is known for its long release cycles ships Python 3.7 already, so if some new features python 3.6+ are considered useful (type hints, f-strings come to my mind), I wouldn't try to keep 3.5 compatibility. :-)

**Comment by pwt** [comment]
> Note that even Debian stable which is known for its long release cycles ships Python 3.7 already, so if some new features python 3.6+ are considered useful (type hints, f-strings come to my mind), I wouldn't try to keep 3.5 compatibility. :-)

Fair point, although Debian 9/Stretch, for which the default Python is 3.5, is supported until June 2022. (I still have machines running Stretch and SoCo).

Unless there's something compelling in 3.6 that we need (or badly want) for SoCo, I don't favour dropping support for 3.5 too hastily.

**Comment by rytilahti** [comment]
> Fair point, although Debian 9/Stretch, for which the default Python is 3.5, is supported until June 2022. (I still have machines running Stretch and SoCo).

Oh, that's new to me, interesting! But indeed, stretch is separately supported by the LTS "subproject" (https://wiki.debian.org/LTS), and there's even ELTS (which supportes still jessie, too). Debian itself has EOL'd both of them already though (https://wiki.debian.org/DebianReleases). 

> Unless there's something compelling in 3.6 that we need (or badly want) for SoCo, I don't favour dropping support for 3.5 too hastily.

Sure thing, I personally like type hints & f-strings for my own personal projects, and use those wherever I can. In the end, I don't personally mind that much, I just thought I'd mention it when I saw this issue in my notifications :-)

**Comment by hugovk** [comment]
Updated! How does this look?

**Comment by pwt** [comment]
> Updated! How does this look?

Looks good -- thanks!

- I've just cleared up some pylint and flake8 issues and pushed the changes to your branch.
- Passes unit and integration tests on Python 3.9.1 and Python 3.5.10.

@KennethNielsen: I'd appreciate if you could take a quick look at this, as it touches a large numbers of files. (In that regard, I think it's similar to the Black formatting changes you made a while ago.) Clears up a lot of Python 2 cruft.

**Review by pwt — APPROVED** [review]

**Comment by pwt** [comment]
Merged. Thanks to @hugovk for initiating this major tidy-up.

**Pull request merged**
