### PR TITLE
Fix for Issue 660 - Properly parse discover

### PR DESCRIPTION
**Pull request by EliSchleifer**
Properly parse discover return messages. Addresses 
https://github.com/SoCo/SoCo/issues/660

### CODE REVIEW

**Comment by KennethNielsen** [comment]
Thanks @EliSchleifer for the patch and @rousseldenis for testing

**Comment by Streetwalrus** [comment]
This change breaks discovery for me, maybe because my device isn't updated. I only use use the line input on my Connect:Amp and rely exclusively on SoCo to control and display the volume on the desktop computer it's connected to. I usually block the device from accessing the internet as well. I'll see if updating resolves the issue, but it's still something you might want to consider fixing.

```
>>> soco.discovery.by_name("La Grotte")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/site-packages/soco/discovery.py", line 226, in by_name
    for device in discover():
  File "/usr/lib/python3.7/site-packages/soco/discovery.py", line 185, in discover
    return zone.visible_zones
  File "/usr/lib/python3.7/site-packages/soco/core.py", line 1026, in visible_zones
    self._parse_zone_group_state()
  File "/usr/lib/python3.7/site-packages/soco/core.py", line 950, in _parse_zone_group_state
    for group_element in tree.find('ZoneGroups').findall('ZoneGroup'):
AttributeError: 'NoneType' object has no attribute 'findall'
```

Similar issue with socos's `list` command.

**Comment by DPH** [comment]
Hi, good observation.

Typically with Sonos people update to the latest version, which is recommended.
The latest version of SoCo works with the latest Sonos. 
If you don't want to update Sonos then you could keep the previous version of SoCo. 

I don't think it is realistic to make the new version backward compatible.
Maybe we should warn people that this is not backward compatible.

Cheers David

**Comment by Streetwalrus** [comment]
Yeah that's perfectly reasonable. I've already updated my device and that fixed it for me so I'll be fine. I know I'm not really using it in the intended way, but it's the only stereo amp I have around so I'll take it until I can replace it.

**Comment by KennethNielsen** [comment]
OK, so a little more info. Sonos 10.1 chaned things in the API, which meant that SoCo stopped working. However, so far only two things **have been found** that were problems. One of the, around favorites, has a fix that **is** backwards compatible. The other, around discovery, has a fix that isn't **but it could be**. I only have limited time to work on SoCo, so I can only commit to try and fix things moving forwards, but it actually should be that difficult to make the discovery backwards compatible. So provided someone wants to put in the work, and attach the old code path with a proper deprecation warning, that I would merge such a PR. Basically ask git for a diff for the discovery function and there then there should be both the old and the new codepath to look at.

**Comment by Streetwalrus** [comment]
Yeah, I understand where you're coming from. Preserving backwards compatibility takes effort and adds cruft to the code base. That said, I would argue that discovery is the bare minimum to keep working to an extent, so that the user would at least get the chance to know why parts of soco might break with their system after an update. I would gladly contribute, but this isn't important enough to me considering I've already updated my system.
At any rate, I don't really have a reason to stay on old firmware, it's just that I _never_ use the sonos app, it's not even installed on my phone and I had to download it to perform the upgrade this time.

**Pull request merged**
