### PR TITLE
Make build_album_art_full_uri public

### PR DESCRIPTION
**Pull request by amelchio**
I think this PR is wrong because obviously a bunch of breaking stuff wasn't just merged on the very day the next release was scheduled.

This makes things work again for my application but I did not have a lot of time to do testing.

CC: @ghcs27

### CODE REVIEW

**Comment by ghcs27** [comment]
Oh, #573 should not have broken any code. What kinds of errors do you get?

**Comment by ghcs27** [comment]
I see what the problem is: The current arguments to the calls don't match the signature given by iter_actions().
We should just revert #573 before the release, and then I'll look into how to make that PR backwards-compatible.

**Comment by amelchio** [comment]
Yes, that was the error I got. Couldn't tell whether that was right or wrong.

Also note the other issue: `self._build_album_art_full_uri` is used by core, but that was removed in #542.

**Comment by ghcs27** [comment]
Could you please remove the changes pertaining to #573? I'll make another PR for that problem.
But we should get the `self._build_album_art_full_uri` changes in.

**Comment by amelchio** [comment]
Okay, I just pushed an updated branch with only the album art changes.

**Comment by amelchio** [comment]
Is it okay to call an underscored method across modules?

**Comment by KennethNielsen** [comment]
@amelchio looks good. Regarding the underscored method. In general no, I think we should promote that method to being public. Since underscored methods are considered internal implementational details, we wont have to worry about backwards compatibility.

**Comment by KennethNielsen** [comment]
@amelchio do you want to add that change to this PR?

**Comment by amelchio** [comment]
Well, I removed the underscores now, not sure if anything is needed documentation wise when making a method public?

Also, I rebased to exclude the service extension fixes that were reverted and I changed the title to make it fit the new content ... it may be better to just open a fresh PR?

Interestingly, `music_library` is calling `self.soco._update_album_art_to_full_uri` (i.e. with an underscore) ...

**Comment by KennethNielsen** [comment]
@amelchio No need for changes documentation wise, if the doc string is clear.

You don't need to open a new PR. The history is clean enough and we can find our way around here.

> Interestingly, music_library is calling self.soco._update_album_art_to_full_uri (i.e. with an underscore) ...

You mean that music_library is calling _update_album_art_to_full_uri on a SoCo instance. That is a mistake and must have been missed during the migration. Probably the most important part of a change like this is grepping though the code to make sure to catch all calls to this methods, no-matter where it comes from.

**Comment by amelchio** [comment]
This is included in #596 so I will close this PR now.

**Pull request closed without merging**
