### PR TITLE
Timeout request

### PR DESCRIPTION
**Pull request by xxdede**
Added a timeout option to ‘requests’ while getting speaker info.

### CODE REVIEW

**Comment by stefankoegl** [comment]
Looks good! The comment describing the parameter should however describe how to disable the timeout. I assume passing ``None`` would work, but this should be stated explicitly.

**Comment by xxdede** [comment]
You're right.

I used the timeout parameter of http://docs.python-requests.org/en/latest/api/#main-interface and it's optional so I think `None` should work.

Probably we can simply remove the default value and let you choose if you want to set a timeout

**Comment by KennethNielsen** [comment]
After quite a bit of searching through requests source code I was able to confirm that it does indeed default to None. @xxdede if you include this information in the docstring like @stefankoegl requested then we should be able to merge and get your change into the next release.

**Comment by xxdede** [comment]
Added doc as suggested!
=)

**Comment by stefankoegl** [comment]
One more thing: ``flake8`` (which is part of the test suite) fails with the following error:

````
soco/core.py:1013:57: E231 missing whitespace after ','
````

When you add the space the build should succeed, and (from my point of view) your change should be ready to be merged.

**Comment by KennethNielsen** [comment]
Merged. Thank you @xxdede for your contribution.

Can you add a comment to the release notes issue #332 that describes your addition?

**Pull request merged**
