### PR TITLE
Add Python 3.6 to travis builds

### PR DESCRIPTION
**Pull request by KennethNielsen**
Python 3.6 has been out for a while. Let's see if it builds, and if it does, add it to the Python versions Travis CI runs our builds on.

### CODE REVIEW

**Comment by KennethNielsen** [comment]
It all checks out. If I can get someones ack on this I'll merge.

**Comment by DPH** [comment]
Fully support adding Python 3.6.
Have not tested it but if it causes no problems lets include it. 

Cheers David

**Comment by KennethNielsen** [comment]
@DPH well, causes no problems with the unit tests anyway. I think that should be good enough.

**Comment by KennethNielsen** [comment]
With no objections and no problems with unit tests I think it seems ok. I'll close this.

**Pull request closed without merging**
