### PR TITLE
Make zone-group-state cache per-household

### PR DESCRIPTION
**Pull request by amelchio**
I am trying to enable multi-household control. A blocker for this is that we currently maintain a global state cache that is invalid when a speaker from a different household is accessed.

This PR removes the global variable and makes the cache per-household.

I moved 10.0.2.14 ("Test") to a separate household. Before this PR:
```
$ python -c 'import soco; a = soco.SoCo("10.0.2.18"); b = soco.SoCo("10.0.2.14"); print(a.player_name); print(b.player_name);'
Kitchen
None
```

After this PR:
```
$ python -c 'import soco; a = soco.SoCo("10.0.2.18"); b = soco.SoCo("10.0.2.14"); print(a.player_name); print(b.player_name);'
Kitchen
Test
```

### CODE REVIEW

**Review by KennethNielsen — APPROVED** [review]
Looks good!

**Comment by KennethNielsen** [comment]
@amelchio it looks great and is ready for merge except that it now has a merge conflict. Can I persuade you to rebase of current master and fix the conflict?

**Comment by pwt** [comment]
I've fixed the merge conflicts and committed the changes to https://github.com/amelchio/SoCo/tree/soco-household-cache. Unfortunately, this breaks my code in discovery:scan_network(), where I disable the cache.

**Comment by pwt** [comment]
This is now passing its checks. I've done a quick test of `scan_network()` against a real network, and it appears to be working fine with multi-households, without needing to enable/disable caching.

@amelchio: Perhaps you could review the changes to check they look OK to you.

**Comment by amelchio** [comment]
Yeah, that looks correct 👍

**Pull request merged**
