### PR TITLE
Fix what broke when the deprecated methods were removed

### PR DESCRIPTION
**Pull request by ghcs27**
I checked the changes I made in #542 and adjusted all calls to the now-removed methods. This is based on @amelchio's work on #576.
Closes #576.

### CODE REVIEW

**Comment by stefankoegl** [comment]
Can I test this somehow, or otherwise help to get this merged?

**Comment by KennethNielsen** [comment]
Hi @ghcs27 

So I reviewed the code changes, and I can't see any problems with them, but I am unable to test any of the affected methods. I think the problem is that this was branches of at that point where you intriduced the kwargs support for the service calls, but this branch doesn't include the fix. So I get something like:

```python
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    s.get_current_track_info()
  File "/home/kenni/venv/soco/SoCo/soco/core.py", line 1158, in get_current_track_info
    ('Channel', 'Master')
  File "/home/kenni/venv/soco/SoCo/soco/services.py", line 210, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/home/kenni/venv/soco/SoCo/soco/services.py", line 468, in send_command
    args = self.compose_args(action, args, kwargs)
  File "/home/kenni/venv/soco/SoCo/soco/services.py", line 356, in compose_args
    .format(next(iter(unexpected)), str(action))
ValueError: Unexpected argument 'Channel'. Method signature: GetPositionInfo(InstanceID: ui4) -> {Track: [0..65535], TrackDuration: string, TrackMetaData: string, TrackURI: string, RelTime: string, AbsTime: string, RelCount: i4, AbsCount: i4}
```

I don't know if this branch can be rebased easily, otherwise I would consider these changes smalle enough to merge without test. Your call.

**Comment by ghcs27** [comment]
Just rebased and hope everything still works.

**Comment by ghcs27** [comment]
Since this is a critical bugfix, I'm merging this now to get it in before the release.

**Pull request merged**
