### PR TITLE
Preliminary speaker info with more information

### PR DESCRIPTION
**Pull request by the01**
Updated the ```get_speaker_info()``` function to parse ```xml/device_description.xml``` as described in #320

- changed zone_icon to player_icon
- added model_number
- added model_name
- added display_version

No unit tests yet

### CODE REVIEW

**Comment by the01** [comment]
My guess is that ```dom.findtext('.//{urn:schemas-upnp-org:device-1-0}device')```returns ```None``` and that is the reason the test fails. Any ideas why this only happens for python 2.6?

**Comment by dundeemt** [comment]
It would be nice to also have, memory, flash, ampOnTime.  Also an option to get the full url to the icon i.e. full_urls=True.

Failing on 2.6 - soco/core.py line 1099  -- I am doing something similar in my helper library but I encode the response from requests using .encode('UTF-8').  Translating to your code... 
```python
dom = XML.fromstring(response.content.encode('UTF-8'))
```
This was cannibalized from the commented out code @ soco/core.py def uid

my helper lib is https://bitbucket.org/dundeemt/chilledsoco/src/66be490323f863eabd6ac3e4fdbd8419b4a12372/chilled.py?at=default  class DeviceProperties

**Comment by the01** [comment]
The question is whether memory, flash,..etc. is really all that important or if we are starting to pollute the speaker_info-dict. For now you can always build the full url with the ```.ip_address```property.
Sadly your proposed fix did not work. I can't get my python2.6 installation up and running properly, so maybe someone with a working env could investigate?

**Comment by lawrenceakka** [comment]
There is a bug in path support in python 2.6. We had some previous discussion about it here: https://github.com/SoCo/SoCo/pull/154 (You may need to view comments on outdated diffs to see it):

> This seems to be a bug in Elementtree < 1.3 (i.e. the version in Python 2.6). Your fix is too widely targeted though, since it testing for xml.etree.ElementTree' in sys.modules will be true for Python 3.

> You are right however that the .// is not in fact needed at all here, since the item element is always an immediate child of the top level element, in this particular case.

> So in fact, the best solution is for you to remove the xml_find_prefix code, and remove the ".//" in all cases where you have otherwise used it. i.e. in your patch, replace

> for item in metadata.findall(self.xml_find_prefix +
    '{urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/}item'): 
with

>  for item in metadata.findall('{urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/}item'): 


One way to handle it might be to find the `device` element, and then conduct a search of its immediate children (i.e. avoid ".//" as much as possible).  I haven't tested this though.

I don't mind including memory, flash etc (though I can't image why anyone would need them), but I'm not keen on the full_urls idea. I agree with @the01 that this can easily be done by the user by combining with the ip address if necessary.



Lawrence

**Comment by dundeemt** [comment]
full_urls @lawrenceakka @the01 is a common idiom in soco.  The argument against it here is the same that could be made else where browse/ search/ and variants have a parameter to specify the full url is returned.  I bring it up for consistency.

As for, those other things in device_description.xml, I can see the point about not polluting the get_speaker_info return structure, but offering access to all of that information, somewhere would be a good thing.  Perhaps, that c/sh ould be a different feature request and pr.
-Jeff

**Comment by the01** [comment]
Maybe I will have another go at the whole 2.6 tests later, though my only way to test this is to do a commit and let travis to its thing. Which is not really optimal for debuging purposes (and makes for an interesting git history :smile: ). So it would be greatly appreciated if someone with a working 2.6 installation could have a look.
Though is it actually necessary to support a platform (2.6) that hasn't seen an update since, I think, 2013? Are there any usage statistics on pypi on which version a package gets installed for?

Maybe a ```get_speaker_info_all()``` whitch does the actual request and returns a dict with all possible entries and ```get_speaker_info()``` uses the all-method instead of requests/lxml and just filters the dict for the values we want?

**Comment by the01** [comment]
Alrigth, the tests finally surrendered, we are good to go :wink:

**Comment by lawrenceakka** [comment]
+1 from me. Please squash a few of the commits, and I'll commit.

Separate PRs for absolute URIs, and for additional info (which I think should be in the same dict), are welcome

**Comment by the01** [comment]
Down to only a single commit

**Comment by lawrenceakka** [comment]
Thanks very much for this.  Please make sure to add a comment on #332 which we will use to create release notes

**Pull request merged**
