### PR TITLE
Add playmodes REPEAT_ONE and SHUFFLE_REPEAT_ONE 

### PR DESCRIPTION
**Pull request by quatauta**
As of version 6.0, Sonos supports playmodes REAPEAT_ONE and SHUFFLE_REPEAT_ONE (http://www.sonos.com/software/release/6-0).

The commits add the new playmodes to soco/alarms.py, soco/core.py, and tests/test_core.py.

### CODE REVIEW

**Comment by KennethNielsen** [comment]
Hallo @quatauta 

This looks good and fairly simple.

The Travis CI tests fail. It looks like a simple style issue about a line being too long. Can you fix that, then I will review and test and we can have it merged.

Regards Kenneth

**Comment by quatauta** [comment]
Hello @KennethNielsen,

Thank you for pointing me to the too long line!

I fixed the too long line in bbe3569.

The Travis CI tests for python 2.6 pass now.

The tests for 2.7, 3.3, 3.4 and pypy still fail. It seems to me, they may fail not because of my changes. Unfortunately, I do not have enough experience with python to judge this.

Please tell If there is more I could/should update.

Regards, Daniel

**Comment by KennethNielsen** [comment]
Thanks for fixing the line.

Yes, the remaining failing tests is due to an updated version of pylint that runs on Travis CI. I have just fixed these in the master branch, so if you want, you can rebase your branch of master.

But if you don't fell up to that, we can also just merge it. I have already tested it, checked that it passes all tests and linting after rebasing.

**Comment by quatauta** [comment]
I never did a rebase but I want to learn. I will give it a try on Saturday or Sunday.

**Comment by KennethNielsen** [comment]
Sounds good. I'd advice you to make an extra branch of the current state of playmode-repeat-one, so that you have something to fall back on if it fails. Other than that, it is not all that complicated. Let me know if you need any help.

**Comment by quatauta** [comment]
I think rebasing was successful. The CI checks do pass.

**Comment by KennethNielsen** [comment]
Looks good. I'll merge it.

Can you please add a short comment to #332 that describes your enhancement and refers to this PR. I'll finally close the PR when we have the release note comment in place.

Thanks for your contribution :)

**Pull request merged**
