### PR TITLE
Fix - audio linein parsing error

### PR DESCRIPTION
**Pull request by PeteRager**
Fix for #964 

In this issue; Sonos is sending a new XML element called "object.item.audioItem.linein" and the XML for this element is causing a parsing error.

Two changes:
- Use XML parser with recovery=True to allow parsing this new event
- Add the new Dldl class to represent the audio line in.

### CODE REVIEW

**Comment by PeteRager** [comment]
Updated code to ignore the XML error. This led to discovering a new DIDL type that was being sent object.item.audioItem.linein; that needed to be defined,

**Comment by pwt** [comment]
Hi Pete: thanks for working on this. Let me know when it's ready to review.

Regarding the check job failures:

1. If you rebase against `master`, that will suppress the Pylint `possibly-used-before-assignment` warnings.
2. That leaves the following to be addressed:
```
************* Module soco.data_structures_entry
soco/data_structures_entry.py:32:13: I1101: Module 'lxml.etree' has no 'XMLParser' member, but source is unavailable. Consider adding this module to extension-pkg-allow-list if you want to perform analysis based on run-time introspection of living objects. (c-extension-no-member)
soco/data_structures_entry.py:33:11: I1101: Module 'lxml.etree' has no 'fromstring' member, but source is unavailable. Consider adding this module to extension-pkg-allow-list if you want to perform analysis based on run-time introspection of living objects. (c-extension-no-member)
soco/data_structures_entry.py:12:0: C0411: third party import "lxml.etree" should be placed before local imports "data_structures.didl_class_to_soco_class", "exceptions.DIDLMetadataError", "xml.ns_tag" (wrong-import-order)
``` 

Cheers,
Peter

**Comment by PeteRager** [comment]
I've fixed the linter / formatting issues, and extended the test, ready for review.

I do have concerns on the changes. While the change to using the parser with recover=True gets us through this specific issue. It does prevent logging exceptions when encountering invalid XML which could make it harder to diagnose future issues.

We could try to parse it with recover=False; if parsing fails - then log a DEBUG message and then parse it with recover=True - this way we'd get the details when debug is turned on; with the benefit of more runtime resilience to Sonos changes.  Could be I'm also overthinking it.

**Comment by pwt** [comment]
Hi @PeteRager : thanks for your work on this; it's now merged and included in SoCo patch release v0.30.5.

Apologies for the long delay.

**Pull request merged**
