### PR TITLE
Make events match events_twisted behavior when port 1400 is unavailable.

### PR DESCRIPTION
**Pull request by bdraco**
Merged downstream as https://github.com/amelchio/pysonos/pull/60

Resolves https://github.com/home-assistant/core/issues/36183

If port 1400 is unavailable, try the next 100 ports
in order to match the behavior in events_twisted.

When multiple Home Assistant instances are running on
the same server, sonos was falling back to polling.  As
support is already available for trying the next port
in events_twisted, this functionality is now extended
to events.

### CODE REVIEW

**Comment by KennethNielsen** [comment]
@bdraco hi, this looks great. We have some other problems with our Travis builds, but it seems like this PR is triggering an error in one of the checks that does work, the black check.

We use black to format all code consistently and check it via Travis before merging. Can I persuade you run black on all the files you changed and push a commit with the changes?

**Comment by KennethNielsen** [comment]
The TravisCI problems mentioned earlier has been fixed which means that now the checks that fail are show problems correctly.

**Comment by bdraco** [comment]
Repushed with `black`

**Comment by KennethNielsen** [comment]
@bdraco thanks! Merged. Please add a comment about to the change to the release notes thread #708

**Pull request merged**
