### PR TITLE
Added play_local_files example

### PR DESCRIPTION
**Pull request by KennethNielsen**
One of the more frequently asked questions is how to play local files. While, as far as I know, it is not possible in the sense that we have found no interface to stream data to the units, we can cheat and just setup a temporary http server with python.

This example shows how, and plays a random file from the current folder on a named Sonos unit.

### CODE REVIEW

**Comment by DPH** [comment]
Great idea for playing local files - well done. 

To date I have used the network path to a file, which works if you know the network path and the path is available for Sonos to read in terms of permissions. Then I can use play_uri with a file name:
for example: 'x-file-cifs://MyNAS/sounds/Tune.mp3'. 

Your approach is more generic
Cheers David

**Comment by stefankoegl** [comment]
Great idea :)

**Comment by KennethNielsen** [comment]
@DPH Yes. I also think it would be a good idea to the question "How do I play local files" to tell people that they should setup a network share and refer them to a few good resources, bacause that solution is much more better in terms of reliability (e.g. the proposed example requires that you keep the python script running to serve the files).

The idea with this, was just to have a entry point with a lower barrier for entrance.

**Comment by KennethNielsen** [comment]
I think since this is just an example and there are a few positive evaluations it should be safe to merge. I will go ahead.

**Pull request merged**
