### PR TITLE
Fix Sonos model bug

### PR DESCRIPTION
**Pull request by arsaboo**
Sonos core.py was not using the right models. Fixes https://github.com/SoCo/SoCo/issues/633

### CODE REVIEW

**Comment by pmac** [comment]
I need this too to support Playbar.  Thanks for the patch.

**Comment by rbdixon** [comment]
Home Assistant bug waiting on this PR being merged: https://github.com/home-assistant/home-assistant/issues/16661

**Comment by pmac** [comment]
I'm using basically your patch, but also filed #637 in case support was needed for the old naming convention (which seems to have been `PLAYBAR`). I'm happy with either solution and am just hoping that some fix is merged and released soon.

**Comment by ghcs27** [comment]
This is probably getting superseded by #637, but this would need a style fix to appease pylint:
```
soco/core.py:791:80: E501 line too long (100 > 79 characters)
soco/core.py:811:80: E501 line too long (100 > 79 characters)
soco/core.py:829:80: E501 line too long (100 > 79 characters)
soco/core.py:849:80: E501 line too long (100 > 79 characters)
```

**Comment by arsaboo** [comment]
Closing it in favor of #637

**Pull request closed without merging**
