### PR TITLE
Drop support for Python 2.6

### LINKED ISSUE #325: Drop support for python 2.6
Quoted from the original description in #263

> From #255
> 
> The new versions of pylint and astroid have dropped support for Python 2.6 (and presumably also for python 3.2). At the moment, we have pinned to old versions in requirements-dev.txt. We will have to decide what to do about our own Python 2.6 support going forward. One option may be to have Travis use different versions of pylon etc for Py2.6, but this seems a bit messy.

For reference, please see the lengthy discussion about the issues pertaining to dropping support for Python 2.6 in #263.

### PR DESCRIPTION
**Pull request by hugovk**
Fixes #325.

Split out from PR https://github.com/SoCo/SoCo/pull/523 ("Drop support for EOL Python 2.6 & 3.3, add support for 3.6") to allow more granular decision making.

### CODE REVIEW

**Comment by KennethNielsen** [comment]
Agreed. +1.

This looks great. Let's get it ASAP.

I guess this comment from @robwebset (https://github.com/SoCo/SoCo/issues/325#issuecomment-340693250) applies to this PR as well. But I would be a favor of pulling anyway, from a code maintainability (and fun features) point of view.

(BTW. If any of you want a horror story along those lines, try reading the code for olefile, which maintains compat back 1.something.extremely.old).

**Comment by KennethNielsen** [comment]
BTW. Just for the point of being thorough. I think we should create a 2.6 branch just before pulling, as the last point of maintaining 2.6 compat.

**Comment by hugovk** [comment]
olefile's more up-to-date than SoCo: 2.7, 3.3+ :)

https://github.com/decalage2/olefile/blob/master/setup.py#L45-L51

**Comment by KennethNielsen** [comment]
@hugovk trust me, that has changed dramatically sometime within the last couple of years.

**Comment by stefankoegl** [comment]
With two approvals and overall consensus on the deprecation, I have now merged the pull request. Thanks everyone for their thoughts and comments!

**Comment by KennethNielsen** [comment]
@stefankoegl did you make a branch beforehand?

**Comment by stefankoegl** [comment]
I've now created branch [`python-2.6`](https://github.com/SoCo/SoCo/tree/python-2.6) at 4dd3ad10c4f524ec9d1a753b619c48ac075f2dc1, which was the commit right before the merge (11515c44332b98b4011c3e07509ba6f54fd32d96).

**Comment by KennethNielsen** [comment]
@stefankoegl thanks

**Pull request merged**
