### PR TITLE
Refactored DidlObject.to_dict() to return the resources element as a …

### PR DESCRIPTION
**Pull request by dundeemt**
…list of dict items instead of DidlResource objects. Also, refactored .from_dict() to expect any

resources to be in dictionary and to make proper DidlResource objects out of them.  Wrote new tests to cover extended functionality. Closes issue #338

### CODE REVIEW

**Comment by KennethNielsen** [comment]
+1 from me

**Comment by lawrenceakka** [comment]
@dundeemt Jeff, Please can you rebase this, and we'll commit.

**Comment by dundeemt** [comment]
done

**Comment by lawrenceakka** [comment]
Thanks Jeff

**Pull request merged**
