### PR TITLE
Allow timeout to be specified on soco.play_uri

### PR DESCRIPTION
**Pull request by PeteRager**
Allow a per call timeout to be set on soco.play_uri - similar to to the existing capability in add_uri_to_queue and add_to_queue.

This capability is needed downstream by the Home Assistant Sonos integration, to allow a longer timeout to be used than the configured default timeout.

https://github.com/home-assistant/core/issues/114936

### CODE REVIEW

**Review by jjlawren — APPROVED** [review]
Looks good!

**Comment by PeteRager** [comment]
I may have the wrong base for this, I think I started with 0.30 fixes, let me know if I need to do something to fix

**Comment by pwt** [comment]
> I may have the wrong base for this, I think I started with 0.30 fixes, let me know if I need to do something to fix

It looks fine to me. There's a couple of unrelated new Pylint warnings, which I'll address separately.
I'll release a patch version (`v0.30.3`) in the next day or two.

**Comment by pwt** [comment]
This change is now included in SoCo `v0.30.3`. Thanks for the contribution.

**Comment by PeteRager** [comment]
Glad to help. Thanks for the quick turn around!

**Pull request merged**
