### PR TITLE
Allow specification of discovery interface. Closes #242

### PR DESCRIPTION
**Pull request by lawrenceakka**
This is based on ideas in #242. It allows an interface address to be specified when using discovery.  Unlike #242 however it requires the user of the SoCo library to specify the interfaces to be used, rather than using the netifaces module to find all the interfaces on the local machine.  This makes the code rather more simple, avoids the need for a dependency, and makes the user responsible for working out which interfaces to use based on knowledge of his or her system.

Thanks to @trollkarlen

### CODE REVIEW

**Comment by robwebset** [comment]
Hi @lawrenceakka please can I suggest a couple of things:
- Is it possible to maybe add a comment to the code with an example of how to get the information to call it - that way we won't lose the work that was done by @trollkarlen and it would make it easier for callers to work out the best way to use this - i.e. a comment covering what get_interfaces used to do with example code
- Can the test added to #242 be reused?

**Comment by stefankoegl** [comment]
+1 to @robwebset's comments, and - apart from that - +1 to the PR :)

**Comment by lawrenceakka** [comment]
@robwebset, 

Comments are no problem - I will add some. But what test are you talking about? 

Lawrence

**Comment by robwebset** [comment]
@lawrenceakka  it looks like there were some test changes:

https://github.com/SoCo/SoCo/pull/242/files#diff-3

**Comment by lawrenceakka** [comment]
All done.  Thanks

**Comment by robwebset** [comment]
Hi All, I know it's closed, but I have just been making use of this - so thanks for the work you both put into this.  As I need to use pretty basic Python (No binaries), I couldn't use "netifaces" so in case it's of any help to anyone else, I ended up doing the following:

```
    # Use the default method to search for Sonos Devices
    try:
        sonos_devices = soco.discover(timeout=5)
    except:
        log("SonosDiscovery: Exception when getting devices")
        log("SonosDiscovery: %s" % traceback.format_exc())
        sonos_devices = []

    # If there are multiple network devices, then this may not have picked up
    # the correct network device to broadcast on, so try another way
    if (sonos_devices is None) or (len(sonos_devices) < 1):
        try:
            # Try and find the address ourselves
            interfaceAddr = socket.gethostbyname(socket.gethostname())
            log("SonosDiscovery: Searching for devices using gethostname %s" % interfaceAddr)
            if interfaceAddr not in [None, '']:
                sonos_devices = soco.discover(timeout=5, interface_addr=interfaceAddr)
        except:
            log("SonosDiscovery: Exception when getting devices")
            log("SonosDiscovery: %s" % traceback.format_exc())
            sonos_devices = []

    # If still not found, try yet another method
    if (sonos_devices is None) or (len(sonos_devices) < 1):
        try:
            # Try and find the address ourselves
            interfaceAddr = socket.gethostbyname(socket.getfqdn())
            log("SonosDiscovery: Searching for devices using getfqdn %s" % interfaceAddr)
            if interfaceAddr not in [None, '']:
                sonos_devices = soco.discover(timeout=5, interface_addr=interfaceAddr)
        except:
            log("SonosDiscovery: Exception when getting devices")
            log("SonosDiscovery: %s" % traceback.format_exc())
            sonos_devices = []

    # If still not found, try the last option
    if (sonos_devices is None) or (len(sonos_devices) < 1):
        try:
            # Try and find the address ourselves by going to a web page
            s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
            s.connect(("sonos.com",80))
            interfaceAddr = s.getsockname()[0]
            s.close()
            log("SonosDiscovery: Searching for devices using web search %s" % interfaceAddr)
            if interfaceAddr not in [None, '']:
                sonos_devices = soco.discover(timeout=5, interface_addr=interfaceAddr)
        except:
            log("SonosDiscovery: Exception when getting devices")
            log("SonosDiscovery: %s" % traceback.format_exc())
            sonos_devices = []
```

Wasn't 100% sure if this is the sort of thing we'd want to include in the default discovery code - so thought I'd post it.

Thanks
Rob

**Pull request merged**
