### PR TITLE
Revision of play_local_files script

### LINKED ISSUE #508: Trying to play local file but getting UPnP Error
I am using Python 2.7  and Soco 0.12 version. I am using play_local_files.py program in my Raspberry pi. But I am getting UPnP exceptions " UPnP Error 711 received: Illegal seek target from 192.168.0.100".

I have tried to print the play_from_queue() function but I am getting "None" intsead of "False" or "True" 

The same script was working in the same Raspberry Pi. But now It is Not working at all.

The Error code:
Traceback (most recent call last):
  File "play_local_files.py", line 106, in <module>
    main()
  File "play_local_files.py", line 99, in main
    add_random_file_from_present_folder(machine_ip, port, zone_name)
  File "play_local_files.py", line 82, in add_random_file_from_present_folder
    zone.play_from_queue(number_in_queue)
  File "/usr/local/lib/python2.7/dist-packages/soco/core.py", line 104, in inner_function
    return function(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/soco/core.py", line 424, in play_from_queue
    ('Target', index + 1)
  File "/usr/local/lib/python2.7/dist-packages/soco/services.py", line 181, in _dispatcher
    return self.send_command(action, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/soco/services.py", line 408, in send_command
    self.handle_upnp_error(response.text)
  File "/usr/local/lib/python2.7/dist-packages/soco/services.py", line 469, in handle_upnp_error
    error_xml=xml_error
soco.exceptions.SoCoUPnPException: UPnP Error 711 received: Illegal seek target from 192.168.0.100

Can anyone help me on this?

### PR DESCRIPTION
**Pull request by KennethNielsen**
It seems that the play_local_files script is popular, but also that people have issues with it. This PR does two things:

 * Fixes the index bug mentioned in #508
 * Improves the script by:

  * Replacing in-script configuration with command line configuration
  * Try and autodetect the local IP-address of the machine
  * Perform more checking when trying to get the zone

Closes #508.

### CODE REVIEW

**Comment by ghcs27** [comment]
Looks great. I'd just move the discovery and associated error checks into the main function, like [this](https://gist.github.com/ghcs27/5261b1a96577d588a6b052f15cb2e08e) (not really necessary, but seems better to me).

**Comment by KennethNielsen** [comment]
Good idea. I incorporated the suggested change. What do you think?

**Comment by ghcs27** [comment]
I'd say this is good to go.

**Comment by KennethNielsen** [comment]
Thanks. Merging.

**Pull request merged**
