### PR TITLE
Add playbar dialog mode support

### PR DESCRIPTION
**Pull request by christiandt**
This PR adds dialog mode for Sonos players that support this feature. Dialog mode will make dialogue easier to hear, which can be especially useful during action movies.

https://sonos.custhelp.com/app/answers/detail/a_id/1959/~/improving-speech-clarity-and-night-time-listening-through-the-playbar

### CODE REVIEW

**Comment by DPH** [comment]
@christiandt - another good addition - same issue I think as in 421
Cheers Daivd

**Comment by KennethNielsen** [comment]
@christiandt agree with @DPH. Same feedback as for #421.

If you make those adjustments this is good to go.

**Comment by christiandt** [comment]
@KennethNielsen All adjustments requested in #421 are now made here as well.

**Comment by christiandt** [comment]
Changes requested in #421 are implemented here as well, so should be ready for merge now :)

**Comment by KennethNielsen** [comment]
@christiandt merged. Thanks for your contribution.

Can you add a note about the change to the release notes issue for the next release (#440)

**Pull request merged**
