### PR TITLE
Remove the methods that were deprecated in 0.12

### PR DESCRIPTION
**Pull request by ghcs27**
Lots of methods were moved from core.py to music_library.py and scheduled for deprecation in the upcoming release 0.14 - this PR removes them as planned.
Closes #367.

### CODE REVIEW

**Comment by KennethNielsen** [comment]
Hi @ghcs27 

Of topic for this particular PR, but would you consider joining our IRC channel (#SoCo on freenode). Since you are quite active, it would be convenient for me to be able to reach you live sometimes, when we are both online.

Regards

**Comment by ghcs27** [comment]
@KennethNielsen Joined!

**Comment by KennethNielsen** [comment]
The changes to core are good to go, but the changes to the tests bother me. It actually has nothing to do with this PR, as those tests should have been moved along with moving the actual music library code. However, I don't think we should delete the test cases. So either they should be:

 1. Put in a test_mulibrary and properly ported
or
 2. Placed there and mark the whole file as "should be skipped" by pytest, until they have been ported and an help wanted issue should be created for actually porting the tests

**Comment by ghcs27** [comment]
Oh... I assumed they had been copied to test_music_library.py, but never checked. I'll try to port them.

**Comment by ghcs27** [comment]
Just realized that #367 ports some of the tests (without moving them), I can use that.

**Comment by KennethNielsen** [comment]
@ghcs27 yeah, but they should still be moved, so that we keep the one test file per source code file correlation. Let me know (on IRC preferably) when it is ready for review.

**Comment by KennethNielsen** [comment]
Merged. Remember to leave a comment about the change in the release notes issue.

**Pull request merged**
