### PR TITLE
Add Deezer support to the sharelink plugin

### PR DESCRIPTION
**Pull request by tipofthesowrd**
I added a DeezerShare link interpreter for the plugin.
Seems to work for albums / playlists / tracks on my end. 

The sharelink is similar to a Spotify sharelink:

deezer:playlist:5390258182

### CODE REVIEW

**Comment by amelchio** [comment]
Awesome, I am happy to see this plugin grow.

Can you clarify, did you invent the `deezer:playlist:5390258182` format? Spotify has its own `spotify:` scheme which is available to share from their app but they are moving away from that and maybe we should stop the proliferation within the plugin at this point.

The intention is to use official share links like `https://www.deezer.com/en/playlist/5390258182` seems to be (though I don't know the Deezer service, only browsed the site just now). This way copy-paste works and one does not have to carefully construct the URI by hand.

**Comment by tipofthesowrd** [comment]
Correct, I set the format to be identical to the Spotify format myself.

In an earlier commit I was using the URL as you described. These work, they
show up when browsing the website (Format:
https://www.deezer.com/playlist/5390258182
<https://www.deezer.com/en/playlist/5390258182>)

However fyi the actual share links from the app generated by Deezer are
being shortened:
https://deezer.page.link/w9zgJuBES9iezNT9A


Op wo 25 aug. 2021 08:32 schreef Anders Melchiorsen <
***@***.***>:

**Comment by pwt** [comment]
If you run `black` on `sharelink.py`, and recommit, that should sort out the check job failures.

**Comment by pwt** [comment]
Looks great! I can't test this myself, so we'll proceed optimistically and assume that your testing generalises.

**Pull request merged**
