### PR TITLE
More logging adjustments

### PR DESCRIPTION
**Pull request by jjlawren**
A followup to #835 to improve logging. Mostly based on what I've encountered when running with Home Assistant.

The `data_structures_entry.py` change is my attempt to work around #599. Open to alternative solutions, of course.

### CODE REVIEW

**Comment by pwt** [comment]
Logging severity adjustments LGTM -- thanks.

@KennethNielsen : Could you take a quick look at the changes to `soco/data_structures_entry.py`?

**Comment by KennethNielsen** [comment]
@pwt

**Review by KennethNielsen — APPROVED** [review]
Ok

**Comment by pwt** [comment]
Thanks @KennethNielsen.

**Pull request merged**
