### PR TITLE
Added remove_sonos_playlist function. 

### PR DESCRIPTION
**Pull request by dundeemt**
Tests written both in test_core using moco and in test_integrations against a device. Closes issue #341.

### CODE REVIEW

**Comment by lawrenceakka** [comment]
Looks good to me.  +1

**Comment by dundeemt** [comment]
I am working on reordering Sonos Playlists for my next PR.  If @KennethNielsen, or other interested parties would like to weigh on this PR so it can be merged too, it would be a great help in writing the tests for reorder_sonos_playlist.

**Comment by lawrenceakka** [comment]
I'll merge this tomorrow if there are no other comments

**Comment by KennethNielsen** [comment]
Hi @dundeemt 

Sorry about the delay. I like that we get some better coverage on Sonos playlists, but I'm unhappy about the input to the function being only the ID. I would prefer it, if most of the time, these internal IDs were invisible to the user. I would therefore suggest that you make the input to the function be either the playlist object (which conatains the ID) or the ID, but with the play list object being the primary input mode.

Another thing that caught my eye is that the underlying call you are using is to ``self.contentDirectory.DestroyObject``, which seems fairly general. Can this be used to delete e.g. tracks from the music collection index? And if so, should we check and deny that or make the method description and name more general?

**Comment by dundeemt** [comment]
Agreed with the object_id vs. Object.   I've written the
reorder_sonos_playlist and friends to accept either a DidlPlaylistContainer,
or any object that has an item_id property (like browse) or the item_id as
a straight string.
I can/will happily update remove_sonos_playlist to have the same
capabilities, but only document / primarily document the object_id
parameter as accepting a DidlPlaylistContainer object.

As far as being more generic, it might well be.  I've been focused on Sonos
Playlists recently, but you are correct in that it "smells" like it might
be able to modify the Queue.  I haven't done much with the queue outside of
use the already existing soco method.  But can/will take a look at it.  Do
we need to make it more discriminating even if it is capable of deleting an
item from the queue? I've not tried to see if it can delete an item from
the library.  (Wouldn't that be transient at best, with the item being
added back during the next library scan?)  If it can, then we can always
refactor and rename it _destroy_object() then make a helper function
remove_sonos_playlist that calls _destroy_object.

Point being, we can refactor later if it is discovered that destroy_object
has more potential than just deleting Sonos Playlists.    Now that I think
about it, you can't delete the queue, it is persistent.

So, I'll make the change to the param to take a DidlPlaylistContainer /
item_id and we can go from there?



I'll update my PR later today

Best,
Jeff

On Wed, Sep 9, 2015 at 2:21 PM, Kenneth Nielsen <notifications@github.com>
wrote:

> Hi @dundeemt <https://github.com/dundeemt>
>
> Sorry about the delay. I like that we get some better coverage on Sonos
> playlists, but I'm unhappy about the input to the function being only the
> ID. I would prefer it, if most of the time, these internal IDs were
> invisible to the user. I would therefore suggest that you make the input to
> the function be either the playlist object (which conatains the ID) or the
> ID, but with the play list object being the primary input mode.
>
> Another thing that caught my eye is that the underlying call you are using
> is to self.contentDirectory.DestroyObject, which seems fairly general.
> Can this be used to delete e.g. tracks from the music collection index? And
> if so, should we check and deny that or make the method description and
> name more general?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SoCo/SoCo/pull/345#issuecomment-139020205>.
>



-- 
Best,

Jeff Hinrichs
dundeemt@gmail.com
402.218.1473

**Comment by lawrenceakka** [comment]
@KennethNielsen Are you happy with this now.  Looks great to me.

L

**Comment by KennethNielsen** [comment]
> I've written the reorder_sonos_playlist and friends to accept either a DidlPlaylistContainer, or any object that has an item_id property (like browse) or the item_id as a straight string.

Great. I like the ```get_attr(playlist, 'item_id', None) or playlist``` I think you did somewhere ;). I will have a look at reorder_sonos_playlist and friends in that PR.

> I can/will happily update remove_sonos_playlist to have the same capabilities, but only document / primarily document the object_id parameter as accepting a DidlPlaylistContainer object.

Yes, please do. I think that would be great. I think however maybe that I expressed myself un-clearly. Besides from making the playlist object the primary input type in the docstring, I think it would be best to also change the name of the input parameter to reflect it. People read documentation differently, some just glance the call spec, so I think it too should reflect the playlist container being the primary input type. So replacing the name of ``object_id`` with the something like ``sonos_playlist``.

Great work with this. With those few minor changes, this is ready to go in.

**Comment by dundeemt** [comment]
PR in line with other PR #352  Have updated doc strings, variable naming and preference for DidlPlaylistContainers.

**Comment by KennethNielsen** [comment]
+1 I'll merge it. Remember to leave a line in the release notes.

**Comment by iloveagent57** [comment]
@dundeemt Thank you for this function!  I had a couple hundred playlists I wanted to delete, and was able to build from master and delete them without issue.

**Pull request merged**
