### PR TITLE
More doc work

### PR DESCRIPTION
**Pull request by KennethNielsen**
This is another PR with a set of fairly large changes to the docs (only dedicated docs, no changes to inline docs though).

The PR includes the following points, which are explained in more detail below:

 1. A new frontpage with small code example and power paragraph loaded with links
 2. Merge tutorial into getting started page and include installation instructions
 3. Move release howto into developments subfolder together with the section on unittesting
 4. Make advanced section and add sections on "Speaker topologies", "UPnP services" and "Events" (cutesy of @stefankoegl)
 5. Add page with micro examples

**1** The new front page is something that I have been wanting to do for a while. What I basically did was to try an figure out, what components the software documentation pages that I really like consist of, and then try to model it from that. The components usually are;

 * Helicopter view description of what the software does
 * Short simple and-to-the-point code example that shows of the strengths of the code
 * A _power paragraph_ that provides a guide to the docs, that is loaded with links
 * The table on contents is pushed all the way to the end, since it is available in the side bar anyway and it is most often not the best way into the docs anyway.

I'm quite satisfied with the result and I hope you like it too.

**2** We didn't really have any installation instructions before and the tutorial was (and I think should be) quite short, so I think it makes sense to merge them

**3** I think docs should make it very clear which doc pages are for people that want to **use** the software and **write** the software respectively, so I moved a few topics if the latter category into their own folder and section. Also because I would like to add more dev topics in the future.

**4** @stefankoegl in #151 wrote pages on a few more in depth topics. These, in my mind, are different from API docs etc. in the sense that, they are more describing some of the underlying concepts that just listing how to use the code, so I think they deserve their own sections and folder. Also here I think a section of their own will make it easier to add more in the future.

**5** The last change is also something that I have been wanting to do for a long time. It is a page of micro examples. Many people prefer to learn from examples (as evident by the popularity e.g. of StackOverflow) so I wanted us to have a huge page with lots and lots of micro examples. This page obviously isn't complete yet, but I wanted this PR merged soon since it touches so many parts of the docs. Also, since I more often have very short time spans to work on SoCo rather than longer stretches, these are something that I can easily see myself working on quite a bit, since it is easy to do just a few examples at a time.

**History** This PR has quite a complicated history. The new sections and also some of the ideas for refactoring came from #151 by @stefankoegl. Stefan ended up giving up on having it merged due to a lack of time to complete it, but I really wanted those new sections in, so I made a new branch and tried to include his work (as announced in #360). This work unfortunately collided with the excellent doc rebasing work by @lawrenceakka in (also discussed in #360), which changed so large parts of the docs that a real rebase seemed impossible. So after having the work sleep in a branch for quite a while, I decided to revive it by doing a manual copy-files-into-new-branch type "rebase" and then I added some of the other things above. This, of course, unfortunately meant that we lost the revision history in it. I have tried the best I can to credit @stefankoegl for the work that he did and I hope I got it right.

I hope you like the work. Comments? Questions?

### CODE REVIEW

**Comment by DPH** [comment]
great initiative, particularly the examples and splitting useage from development. 
Not read through it all but as it is documentation we should pull it ASAP and on develop from there. 

Cheers Daivd

**Comment by KennethNielsen** [comment]
It would be great if someone had the time to give this a look at some point since it touches so many files that it will quickly develop conflicts.

**Comment by lawrenceakka** [comment]
Hi @KennethNielsen .  This looks fantastic to me.  I will provide a couple of small comments over the next few days - I am not well today :cry:

**Comment by KennethNielsen** [comment]
Thanks. No rush right now. I'll be here (http://www.roskilde-festival.dk) for the next week ;)

**Comment by KennethNielsen** [comment]
Hope you feel better

**Comment by KennethNielsen** [comment]
If anyone if up for it, it would be great with a review of this. It's fairly big and I would rather that it didn't go stale.

**Comment by robwebset** [comment]
I'm not great at proof reading docs - my general feeling is - if it's more docs - get it in - and then let people tweak and add comments later (When reading them on the live system) - as you've done lots of the code - I think it's better to have them as they are ASAP for people to see!

**Comment by DPH** [comment]
@KennethNielsen great work - have read through and it is very helpful. Can't see any problems in pulling it now. 

I do think we could all help by adding to the examples directory. often if I answer a question I will send an example of how to do something. I should add this to the examples directory for all to see. 

Documentation on subscription is great - again we could add in the future some documentation on the cache feature for zone groupings, which I am still not sure how it works!

However as @robwebset says - lets get it live as is rather than wait - it will help people. Well done
Cheers David

**Comment by KennethNielsen** [comment]
@robwebset The thing is, that this PR is not only about adding, but also changing (organisation mostly), where I guess the evaluation of the quality is more subjective. "Do I like this organisation of the doc page". Which I why I wanted feedback. Other than that I agree, more docs is better.

**Comment by KennethNielsen** [comment]
@DPH I agree. So, the section with micro examples are meant to be just that, so they basically should be very micro, lot's of those, that I hope everybody will help with. But in general, also more of the full fledged examples both in code and in the docs would also be great to have more of. Some people prefer to learn like that. I think in the long run, we should also add a FAQ, since I see a lot of the same questions asked.

**Comment by KennethNielsen** [comment]
@DPH and thanks for the review.

@lawrenceakka Did you want to comment on this now? Or should we just pull it and do the rest later?

**Comment by lawrenceakka** [comment]
@KennethNielsen Really sorry - I did say I would comment on this a while ago, but I was ill with 'flu for three weeks ( 😷 ) and then busy catching up with work!  I have read it through and I definitely think it should be committed now. There are a few typos etc (I wish my Danish was as good as your English) but it is easier to correct those later.

**Comment by KennethNielsen** [comment]
@lawrenceakka No problem. I will see if I can find the typos, rebase (and fix whatever conflict there is) and merge. Thanks.

**Comment by KennethNielsen** [comment]
I rebased and fixd a few typos. Ready to merge efter travis says ok.

**Comment by KennethNielsen** [comment]
flake8 no linger supports Python 2.6, so I had to disable the check to get the tests to pass. I'll merge it including this change.

**Pull request merged**
