### PR TITLE
Add plugin for playback of Spotify & Tidal ShareLinks

### PR DESCRIPTION
**Pull request by amelchio**
This is a different take on supporting music services. It is a bit rough so I placed it in a plugin.

The plugin allows playing from the "share links" that some music services provide. No authentication step is needed but the matching music service must be installed on Sonos. 

Supported link formats:
* `https://open.spotify.com/track/6cpcorzV5cmVjBsuAXq4wD`
* `spotify:album:6wiUBliPe76YAVpNEdidpY`
* `https://tidal.com/browse/album/157273956`

The constructed message data was found with Wireshark while pressing play in the native app. I have no idea what it means but it does work :). Adding other services is probably straightforward but it requires an active account in order to do the network dump.

There is a US and a non-US Spotify service so the service ID is looked up dynamically. I have only been able to test this version of the code on non-US Spotify; if someone can test with US Spotify and TIDAL, that would be great.

```python
>>> from soco import SoCo
>>> from soco.plugins.sharelink import ShareLinkPlugin
>>> speaker=SoCo("10.0.2.13")
>>> sharelink=ShareLinkPlugin(speaker)
>>> sharelink.add_share_link_to_queue("https://open.spotify.com/album/14IYDXybb1XKu51QHDryak")
1
```

### CODE REVIEW

**Comment by pwt** [comment]
Works nicely for me with Spotify (UK).

**Comment by KennethNielsen** [comment]
This looks interesting. I will review it as soon as I can find the time.

**Comment by amelchio** [comment]
> There is a US and a non-US Spotify service so the service ID is looked up dynamically.

I just pushed an amendment to also lookup TIDAL dynamically, that makes it all look less rough.

**Comment by acatoire** [comment]
I just try it on FR spotify with success, this is a great step for app with very little interaction related to spotify.

**Comment by pwt** [comment]
> I just try it on FR spotify with success, this is a great step for app with very little interaction related to spotify.

I'm confident we'll get this in to SoCo 0.23 -- due to be released in about a month.

**Comment by pwt** [comment]
Note: check jobs failing due to new "consider" warning introduced in Pylint 2.9.

**Comment by pwt** [comment]
No further comments on this, initial testing looks good, and it's already in use in Home Assistant, so I'm going to merge this to land in v0.23.

**Comment by tipofthesowrd** [comment]
For Deezer I found the following, where the aplaylist is corresponding to the Deezer Platylist number
or  x-rincon-cpcontainer:1006006calbum-153993652 when trying to play a specific album

```
    <s:Envelope
        xmlns:s="http://schemas.xmlsoap.org/soap/envelope/"
        s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
        <s:Body>
            <u:AddURIToQueue
                xmlns:u="urn:schemas-upnp-org:service:AVTransport:1">
                <InstanceID>
                    0
                    </InstanceID>
                <EnqueuedURI>
                    x-rincon-cpcontainer:1006006cplaylist_spotify%3aplaylist-6122724024?sid=2&amp;flags=108&amp;sn=3
                    </EnqueuedURI>
                <EnqueuedURIMetaData>
                     [truncated]&lt;DIDL-Lite xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot; xmlns:r=&quot;urn:schemas-rinconnetworks-com:metadata-1-0/&quot; xmlns=&quot;urn:schemas-upnp-o
                    </EnqueuedURIMetaData>
                <DesiredFirstTrackNumberEnqueued>
                    0
                    </DesiredFirstTrackNumberEnqueued>
                <EnqueueAsNext>
                    0
                    </EnqueueAsNext>
                </u:AddURIToQueue>
            </s:Body>
        </s:Envelope>

```

**Pull request merged**
