### PR TITLE
Initial Commit:  Plugin works for my single speaker system. I attempted ...

### PR DESCRIPTION
**Pull request by jlmcgehee21**
I attempted to build this for multiple speaker systems, but I have no way to test/troubleshoot it.

I'm not sure if this fits your programming style, but I tried my best.  I would love for someone with multiple speakers to test/add to this.  It may be a little while before I add speakers to my system.

The main purpose of this for me is to link it with my DIY home automation system.  I wanted to contribute to what I feel is a great project instead of just branching out on my own.

-Jeff McGehee

### CODE REVIEW

**Comment by DPH** [comment]
Version 0.10 of SoCo has all the stuff you need (snapshot, whole lot of fixes etc.)
It can be installed as any other Python package: https://pypi.python.org/pypi/soco/

The speaking bit needs to  either be in you own code, based on the examples out there, or be made into a plugin for general use. 

Hope this helps, Cheers David

**Comment by KennethNielsen** [comment]
Hi @jlmcgehee21 and thanks for putting the stuff out here.

I'm a little in doubt about the status here, and the text-to-speech stuff is not my strong suit. Does this plugin represent functionality not already in SoCo (@jlmcgehee21, @robwebset, @DPH). At first glance I would say that it does, since it seems most of the existing text-to-speech stuff has been external scripts and this is made as a proper plugin. It might of course be very useful for @jlmcgehee21 to have a look at the code @robwebset published in #99, so if you want to continue working on the plugin and make a PR later, we can also do that.

I just wanted to check before I started reviewing.

**Comment by jlmcgehee21** [comment]
After some review of the code in #99 and more testing with my pull request,
I think the best solution would be to modify #99 to function as a proper
plugin.  The use of the Snapshot class (which I didn't even realize existed
until I got some responses to my pull request) is much better than what I
tried to hack together.

My plan is to implement #99 as a plugin when I find some free time and
submit a new pull request then.  I think I'll go ahead and close this one.
Thanks for the awesome work you guys are doing!

**Comment by KennethNielsen** [comment]
That sounds like a great plan.

One thing that might help you, with your next PR. We tend to stay pretty close with the python programming style defined in pep8 and by pylint, and I noticed quite a few style problems when I glanced this PR, which you would have to fix to get a PR pulled. So I would advice you to run pylint and pep8 checks on your code as you develop, to get to know the guide lines and to not have to worry about that in the review. You should note though, that we don't follow pylint **religiously**. Checks can be disabled, and there can be valid reasons to do so, but not very many ;)

Let us know if you run into problems running pylint and pep8 checks, that you can't information on with google.

**Comment by jlmcgehee21** [comment]
Thanks for the tips. I have been developing with PyCharm which makes pep8
based suggestions.  I guess it's time that I stop ignoring them ;)

I do scientific coding professionally, so for the most part, any given
piece of code only needs to live long enough for me to get an answer.  It's
good for me to see/learn some proper developing techniques.

I saw that the existing plugins are coded with a heavy use of decorators.
Is that preferred styling for SoCo as well?  Just want to make any future
pull requests as painless as possible.

**Comment by KennethNielsen** [comment]
I have a similar background to you (scientific and not trained as a software developer ;)), so feel free to take it with a grain of salt when regarding any advice that I give as "proper developing techniques" :D

I'm not sure which decorators you are referring to ``@staticmethod`` and ``@classmethod`` serve a particular purpose, but most likely what you have noticed are ``@property`` decorators. No, we have no preference for using decorators especially much, we use them when they serve a purpose. The ``@property`` for instance, is useful if you have a method, that essentially acts like a property (i.e. essentially just for reading out a value of something) but where the value needs to be calculated. I think probably the best example of the use of ``@property`` is the fictional ``Circle`` class, where you store the radius internally, but implement the diameter as a property. So, to put it shortly, no, we just use them when it makes sense (the cases above or any other time you need to wrap a functions in a start and end). Also, one should be careful about not overusing decorators, because they 'hide' code from plain sight and therefore can make it more difficult to read.

**Pull request closed without merging**
