### PR TITLE
Add is_soundbar property and support all soundbars

### LINKED ISSUE #633: Night_mode and dialog_mode not supported on Playbase
I just tried changing the `night_mode` and `dialog_mode` on my Playbase, but get an error for both as not supported. I can change these modes from the Sonos app, so looks like it is a SoCo limitation. 

```
>>> my_zone
SoCo("192.168.2.253")
>>> my_zone.get_speaker_info()
{u'display_version': '9.1', u'player_icon': '/img/icon-S11.png', u'uid': 'RINCON_XYZ', u'software_version': '45.1-56150', u'mac_address': u'MA-CA-DD-RE-S-S', u'hardware_version': '1.14.1.11-1', u'model_number': 'S11', u'serial_number': 'MA-CA-DD-RE-S-S:1', u'zone_name': 'Family Room', u'model_name': 'Sonos Playbase'}
>>> my_zone.night_mode = True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/soco/core.py", line 813, in night_mode
    raise NotSupportedException(message)
soco.exceptions.NotSupportedException: This device does not support night mode
>>> my_zone.dialog_mode = True
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/soco/core.py", line 851, in dialog_mode
    raise NotSupportedException(message)
soco.exceptions.NotSupportedException: This device does not support dialog mode
```

Let me know if you need any other details

### PR DESCRIPTION
**Pull request by pmac**
Fix support for Playbar, and add for Playbase and Beam.

Fix #633

### CODE REVIEW

**Comment by ghcs27** [comment]
+1 :+1:
I really like the extracted property, removing that quadruplicate code.

**Comment by ghcs27** [comment]
One minor nitpicky suggestion: I'd move `SOUNDBARS` to the bottom, together with `NS` and `PLAY_MODES`.

**Comment by pmac** [comment]
@ghcs27 great suggestion. I hadn't noticed that there was a section for constant definition in the file. I've moved it, and also changed the detection to `endswith()` instead of `in` to avoid the possibility that some future product has e.g. the word "beam" elsewhere in it.

**Comment by pmac** [comment]
doh! broke tests. working on that now.

**Comment by pmac** [comment]
Tests (hopefully) fixed

**Comment by ghcs27** [comment]
Great work! If there are no objections, I will merge this next week.

**Comment by pmac** [comment]
Thanks for taking a look!

**Comment by ghcs27** [comment]
Merged! Thank you for your contribution, @pmac!

Please do not forget to add a summary of the changes to the release notes in #629!

**Comment by pmac** [comment]
> Please do not forget to add a summary of the changes to the release notes in #629!

Done. Thanks again!

**Pull request merged**
