### PR TITLE
Added household_id as optional parameter. 

### PR DESCRIPTION
**Pull request by twosky2000**
Use byte code b'Sonos_7O********************R7eU' from X-RINCON-HOUSEHOLD: Sonos_7O********************R7eU.

### CODE REVIEW

**Comment by twosky2000** [comment]
Sorry for breaking lint. I'm new and would like tips for making my programming style better.

**Comment by pwt** [comment]
Note that #733 covers the underlying requirement here. It allows for multi-household discovery, and scanning the network for Sonos devices is the only way I know of finding all households.

Should we close this PR?

**Comment by pwt** [comment]
I'm going to close this PR, as multi-households are quite well supported in SoCo 0.21 (to be released shortly).

Use the `network_scan` variants of the discover commands (with `multi_household=True`) to ensure that all households are discovered.

**Comment by pwt** [comment]
Note: I've resurrected this feature in PR #939.

**Pull request closed without merging**
